name: PR Tests

on:
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore ./Deface.NET/tests/Deface.NET.UnitTests

    - name: Run Unit Tests
      run: dotnet test ./Deface.NET/tests/Deface.NET.UnitTests --no-restore --verbosity normal

  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Install FFmpeg
      uses: federicocarboni/setup-ffmpeg@v3

    - name: Restore dependencies
      run: dotnet restore ./Deface.NET/tests/Deface.NET.IntegrationTests

    - name: Run Integration Tests
      run: dotnet test ./Deface.NET/tests/Deface.NET.IntegrationTests --no-restore --verbosity normal
